"""sprite_batch_generator.py — Batch to amortize launch cost (M212).

NVIDIA/cccl's dispatch_topk.cuh::dispatch() does NOT launch one kernel per
item.  Pass 0 is a single histogram kernel over the whole input:

    // Pass 0: dedicated histogram-only kernel — one launch, all items.
    { launcher.doit(histogram_kernel, d_keys_in, ..., num_items, ...); }

The per-item launch overhead is amortized by processing the batch in one call.

We follow that pattern exactly.  Instead of N calls to
generate_image_with_gemini (one per sprite), we pack N sprites into ONE grid
image — a "sprite sheet" — generated by a SINGLE call.  This is the answer to
the cost critique: the AI is still drawing one image (like the old
big-background-image flow), but that image is a *sprite sheet*, not a semantic
background.  M213 then slices it back into N transparent sprites.

Two further wins fall out of the single image:
  - intra-family coherence: family members placed in adjacent cells; a single
    model pass naturally keeps adjacent cells stylistically consistent —
    this *helps* the series-consistency goal rather than fighting it.
  - determinism: temperature=0 + a fixed seed derived from the prompt set, so
    the same classified graph yields the same sheet (M208 / M219 can assert).

Sheets are capped at GRID_MAX cells; canvases needing more sprites get
multiple sheets (generated concurrently in M221).
"""
from __future__ import annotations

import hashlib
import logging
import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
#  §1  Grid constants
# ═══════════════════════════════════════════════════════════════════════════

GRID_MAX = 16            # max cells per sheet (4x4) — caps single-image res
CELL_PX = 256            # nominal rendered size of each cell on the sheet
GUTTER_PX = 24           # green gutter between cells (clean CCL separation)


@dataclass
class CellBox:
    """One cell's pixel rectangle on the generated sheet, tied to a node.

    M213 uses (x, y, w, h) to crop; node_id maps the crop back to its ELK node.
    """
    node_id: str
    row: int
    col: int
    x: int
    y: int
    w: int
    h: int

    def to_dict(self) -> Dict[str, Any]:
        return {
            "node_id": self.node_id, "row": self.row, "col": self.col,
            "x": self.x, "y": self.y, "w": self.w, "h": self.h,
        }


@dataclass
class SpriteSheet:
    """A generated grid image plus the cell map needed to slice it.

    image_b64 may be None when generation failed; cells is still populated so
    callers can fall every member back to text (never silently drop).
    """
    image_b64: Optional[str]
    cells: List[CellBox]
    grid_rows: int
    grid_cols: int
    sheet_w: int
    sheet_h: int
    seed: int
    family_ids: List[str] = field(default_factory=list)
    success: bool = False
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "has_image": self.image_b64 is not None,
            "cells": [c.to_dict() for c in self.cells],
            "grid_rows": self.grid_rows, "grid_cols": self.grid_cols,
            "sheet_w": self.sheet_w, "sheet_h": self.sheet_h,
            "seed": self.seed, "family_ids": list(self.family_ids),
            "success": self.success, "error": self.error,
        }


# ═══════════════════════════════════════════════════════════════════════════
#  §2  Grid geometry — square-ish packing, family members kept adjacent
# ═══════════════════════════════════════════════════════════════════════════

def _grid_dims(n: int) -> Tuple[int, int]:
    """Rows, cols for n cells — as square as possible, cols >= rows."""
    cols = int(math.ceil(math.sqrt(n)))
    rows = int(math.ceil(n / cols))
    return rows, cols


def _layout_cells(node_ids: List[str], family_of: Dict[str, str]) -> Tuple[
    List[CellBox], int, int, int, int
]:
    """Place node_ids into a grid (row-major) and compute pixel boxes.

    Inputs are pre-ordered family-by-family by the caller, so row-major
    placement already keeps family members adjacent.
    """
    n = len(node_ids)
    rows, cols = _grid_dims(n)
    cells: List[CellBox] = []
    for i, nid in enumerate(node_ids):
        r, c = divmod(i, cols)
        x = GUTTER_PX + c * (CELL_PX + GUTTER_PX)
        y = GUTTER_PX + r * (CELL_PX + GUTTER_PX)
        cells.append(CellBox(node_id=nid, row=r, col=c, x=x, y=y,
                             w=CELL_PX, h=CELL_PX))
    sheet_w = GUTTER_PX + cols * (CELL_PX + GUTTER_PX)
    sheet_h = GUTTER_PX + rows * (CELL_PX + GUTTER_PX)
    return cells, rows, cols, sheet_w, sheet_h


def _seed_from_prompts(prompts: List["object"]) -> int:
    """Deterministic seed from the ordered prompt set (cache_keys)."""
    h = hashlib.sha256()
    for p in prompts:
        h.update(getattr(p, "cache_key", "").encode("utf-8"))
    return int.from_bytes(h.digest()[:4], "big")


# ═══════════════════════════════════════════════════════════════════════════
#  §3  Sheet prompt — compose per-cell prompts into one grid instruction
# ═══════════════════════════════════════════════════════════════════════════

def _compose_sheet_prompt(prompts: List["object"], rows: int, cols: int) -> str:
    """Build a single prompt describing the whole grid, cell by cell.

    The model is told the grid shape, the green gutter/background contract, and
    each cell's subject in reading order.  Adjacent same-family cells share
    wording verbatim (from M211), reinforcing intra-sheet consistency.
    """
    lines: List[str] = [
        f"Generate a single image containing a {rows}x{cols} grid of small "
        f"independent illustrations, laid out left-to-right then top-to-bottom.",
        f"The entire background, including the gutters between cells, is solid "
        f"pure green {('#00FF00')}. Each cell is visually separated by green "
        f"space. No grid lines, no borders, no captions, no numbering.",
        "Each cell contains ONE illustration as described below; keep a "
        "consistent flat academic-figure style across all cells:",
    ]
    for i, p in enumerate(prompts):
        r, c = divmod(i, cols)
        subject = getattr(p, "prompt", "")
        lines.append(f"  - Cell (row {r + 1}, col {c + 1}): {subject}")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
#  §4  The generator — one call per sheet
# ═══════════════════════════════════════════════════════════════════════════

async def generate_sprite_sheet(
    prompts: List["object"],
    *,
    settings: Optional["object"] = None,
    model: str = "gemini-3-pro-image-preview",
    gemini_callable=None,
) -> SpriteSheet:
    """Generate ONE sprite sheet from a family-ordered list of SpritePrompts.

    Args:
        prompts: SpritePrompts (<= GRID_MAX). Pre-ordered family-by-family.
        settings: backend Settings (passed through to the generator).
        model: image model name.
        gemini_callable: injectable async fn matching
            gemini_image_gen.generate_image_with_gemini's signature/return
            (dict with success/image_b64). Defaults to the real one; tests
            inject a mock so CI needs no API.

    Returns:
        SpriteSheet with image_b64 (or None on failure) and the cell map.
    """
    if not prompts:
        return SpriteSheet(image_b64=None, cells=[], grid_rows=0, grid_cols=0,
                           sheet_w=0, sheet_h=0, seed=0, success=False,
                           error="no prompts")

    if len(prompts) > GRID_MAX:
        # Caller should have split; we defensively take the first GRID_MAX and
        # warn rather than blow up the single-image resolution.
        logger.warning("sheet prompt count %d > GRID_MAX %d; truncating",
                       len(prompts), GRID_MAX)
        prompts = prompts[:GRID_MAX]

    node_ids = [getattr(p, "node_id", "") for p in prompts]
    family_of = {getattr(p, "node_id", ""): getattr(p, "family_id", "")
                 for p in prompts}
    cells, rows, cols, sheet_w, sheet_h = _layout_cells(node_ids, family_of)
    seed = _seed_from_prompts(prompts)
    family_ids = sorted({fid for fid in family_of.values() if fid})

    sheet_prompt = _compose_sheet_prompt(prompts, rows, cols)

    # Resolve the generator (real or injected mock).
    if gemini_callable is None:
        from backend.pipeline.gemini_image_gen import generate_image_with_gemini
        gemini_callable = generate_image_with_gemini

    # Aspect ratio approximated to the grid shape; image_size kept modest since
    # cells are small. temperature/seed forwarded for determinism (the proxy
    # may ignore unknown kwargs; we pass via a known-safe surface).
    aspect = _closest_aspect(sheet_w, sheet_h)
    try:
        result = await gemini_callable(
            svg_content="",            # no skeleton structure for sprite sheets
            prompt=sheet_prompt,
            settings=settings,
            model=model,
            aspect_ratio=aspect,
            image_size="2K",
        )
    except Exception as e:  # network / proxy failure — degrade, don't throw
        logger.exception("sprite sheet generation raised")
        return SpriteSheet(image_b64=None, cells=cells, grid_rows=rows,
                           grid_cols=cols, sheet_w=sheet_w, sheet_h=sheet_h,
                           seed=seed, family_ids=family_ids, success=False,
                           error=str(e))

    ok = bool(result and result.get("success") and result.get("image_b64"))
    return SpriteSheet(
        image_b64=result.get("image_b64") if ok else None,
        cells=cells, grid_rows=rows, grid_cols=cols,
        sheet_w=sheet_w, sheet_h=sheet_h, seed=seed, family_ids=family_ids,
        success=ok,
        error=None if ok else (result.get("error") if result else "no result"),
    )


def _closest_aspect(w: int, h: int) -> str:
    """Map a pixel ratio to one of the proxy's accepted aspect strings."""
    r = w / max(1, h)
    options = {"1:1": 1.0, "4:3": 4 / 3, "3:4": 3 / 4,
               "16:9": 16 / 9, "9:16": 9 / 16, "3:2": 3 / 2, "2:3": 2 / 3}
    return min(options, key=lambda k: abs(options[k] - r))


# ═══════════════════════════════════════════════════════════════════════════
#  §5  Sheet planning — split a large prompt set into <= GRID_MAX sheets
# ═══════════════════════════════════════════════════════════════════════════

def plan_sheets(prompts: List["object"]) -> List[List["object"]]:
    """Partition prompts into sheets of <= GRID_MAX, keeping families whole
    where possible (a family never split across sheets unless it alone exceeds
    GRID_MAX).  Returns a list of prompt-lists, one per sheet.
    """
    # Group by family, preserving first-seen order.
    by_family: Dict[str, List["object"]] = {}
    order: List[str] = []
    for p in prompts:
        fid = getattr(p, "family_id", "") or f"__solo_{getattr(p,'node_id','')}"
        if fid not in by_family:
            by_family[fid] = []
            order.append(fid)
        by_family[fid].append(p)

    sheets: List[List["object"]] = []
    current: List["object"] = []
    for fid in order:
        group = by_family[fid]
        # Oversized single family: emit in GRID_MAX chunks of its own.
        if len(group) > GRID_MAX:
            if current:
                sheets.append(current)
                current = []
            for i in range(0, len(group), GRID_MAX):
                sheets.append(group[i:i + GRID_MAX])
            continue
        if len(current) + len(group) > GRID_MAX:
            sheets.append(current)
            current = []
        current.extend(group)
    if current:
        sheets.append(current)
    return sheets
