// ═══════════════════════════════════════════════════════════════════════════════
// M013: Cell Asset Loader — PixiJS Assets pipeline for species textures & MSDF
//
// Mirrors upstream/pixijs-engine/src/assets/Assets.ts loader architecture.
// Provides async preloading of:
//   1. Species icon textures (from CIL icon SVGs → MSDF atlas)
//   2. MSDF font atlases (from backend/pipeline/msdf_gen.py output)
//   3. Species colour palettes (from SPECIES_METADATA JSON endpoint)
//
// Like activetheory.net: all assets loaded before first render,
// progress callback drives loading bar UI.
// ═══════════════════════════════════════════════════════════════════════════════

import { Assets, type ProgressCallback } from 'pixi.js';
import type { Texture, Spritesheet } from 'pixi.js';

// ── Species manifest ────────────────────────────────────────────────────────

/** Species icon texture keys — matches channels/rendering/species/species_port.py */
const SPECIES_ICON_KEYS = [
  'cil-eye', 'cil-vector', 'cil-bolt', 'cil-plus', 'cil-arrow-right',
  'cil-filter', 'cil-code', 'cil-layers', 'cil-loop', 'cil-graph',
] as const;

export type SpeciesKey = typeof SPECIES_ICON_KEYS[number];

/** Loaded species assets cache */
export interface SpeciesAssets {
  icons: Record<SpeciesKey, Texture>;
  msdfAtlas: Texture | null;
  msdfFontData: Record<string, unknown> | null;
  palette: Record<SpeciesKey, { fill: number; stroke: number; glow: number }>;
}

// ── Asset bundle definition ─────────────────────────────────────────────────

function buildSpeciesBundle(basePath: string) {
  const bundle: Record<string, string> = {};

  for (const species of SPECIES_ICON_KEYS) {
    // MSDF textures generated by backend/pipeline/msdf_gen.py
    bundle[`icon-${species}`] = `${basePath}/msdf/${species}.png`;
  }

  // MSDF font atlas for cell labels
  bundle['msdf-atlas'] = `${basePath}/msdf/font-atlas.png`;
  bundle['msdf-font-data'] = `${basePath}/msdf/font-atlas.json`;

  // Species metadata (colours, F0, roughness)
  bundle['species-metadata'] = `${basePath}/api/species-metadata.json`;

  return bundle;
}

// ── Colour conversion ───────────────────────────────────────────────────────

function hexToNumber(hex: string): number {
  return parseInt(hex.replace('#', ''), 16);
}

function buildPalette(metadata: Record<string, { color: string; bg_color: string }>):
  Record<SpeciesKey, { fill: number; stroke: number; glow: number }> {
  const palette = {} as Record<SpeciesKey, { fill: number; stroke: number; glow: number }>;

  for (const species of SPECIES_ICON_KEYS) {
    const meta = metadata[species];
    if (meta) {
      const fill = hexToNumber(meta.color);
      palette[species] = {
        fill,
        stroke: hexToNumber(meta.bg_color),
        glow: fill,
      };
    } else {
      palette[species] = { fill: 0x666666, stroke: 0xCCCCCC, glow: 0x666666 };
    }
  }

  return palette;
}

// ── Main loader ─────────────────────────────────────────────────────────────

let _cachedAssets: SpeciesAssets | null = null;

/**
 * Preload all species assets using PixiJS Assets pipeline.
 *
 * Call once before first render. Returns structured assets object.
 * Subsequent calls return cached result.
 *
 * @param basePath - Base URL for asset files (default: current origin)
 * @param onProgress - Loading progress callback (0.0 → 1.0)
 */
export async function loadCellAssets(
  basePath = '',
  onProgress?: ProgressCallback,
): Promise<SpeciesAssets> {
  if (_cachedAssets) return _cachedAssets;

  // Register asset bundle
  const bundleId = 'cell-species';
  const bundle = buildSpeciesBundle(basePath);

  Assets.addBundle(bundleId, bundle);

  // Load all assets with progress tracking
  const loaded = await Assets.loadBundle(bundleId, onProgress);

  // Build icons map
  const icons = {} as Record<SpeciesKey, Texture>;
  for (const species of SPECIES_ICON_KEYS) {
    const key = `icon-${species}`;
    icons[species] = loaded[key] ?? null;
  }

  // MSDF atlas
  const msdfAtlas: Texture | null = loaded['msdf-atlas'] ?? null;
  const msdfFontData: Record<string, unknown> | null = loaded['msdf-font-data'] ?? null;

  // Species palette from metadata
  const metadata = loaded['species-metadata'] ?? {};
  const palette = buildPalette(metadata);

  _cachedAssets = { icons, msdfAtlas, msdfFontData, palette };
  return _cachedAssets;
}

/**
 * Get cached assets (throws if not yet loaded).
 */
export function getCellAssets(): SpeciesAssets {
  if (!_cachedAssets) {
    throw new Error('[cell-asset-loader] Assets not loaded. Call loadCellAssets() first.');
  }
  return _cachedAssets;
}

/**
 * Invalidate cache and force reload on next loadCellAssets() call.
 */
export function invalidateCellAssets(): void {
  _cachedAssets = null;
}

/**
 * Background-load remaining non-critical assets after first render.
 * Uses PixiJS BackgroundLoader pattern from upstream.
 */
export async function backgroundLoadExtras(basePath = ''): Promise<void> {
  // Preload spritesheet variants for different screen densities
  const extras = {
    'species-sheet-2x': `${basePath}/msdf/species-sheet@2x.json`,
    'species-sheet-1x': `${basePath}/msdf/species-sheet@1x.json`,
  };

  Assets.addBundle('cell-extras', extras);
  await Assets.backgroundLoadBundle('cell-extras');
}
