// src/lib/sph/morphogenesis.ts
//
// L-system plant-growth morphogenesis — procedural edge paths for the
// cell pub-sub graph.  Each graph edge becomes a living branch generated by
// a Lindenmayer system; particles then stream along the resulting Bézier
// spline just as sap flows through a stem.
//
// ─── Algorithm overview ──────────────────────────────────────────────────────
//   1. AXIOM + RULES → string expansion (configurable depth).
//   2. Turtle interpreter converts symbol string → sequence of (x,y,angle)
//      waypoints with optional branching stack.  Only the trunk path (stack
//      depth 0) is kept as the primary edge spine; branches up to
//      maxBranchDepth are appended as secondary spurs.
//   3. Waypoints → cubic Bézier segments using Catmull-Rom → Bézier
//      conversion so the curve passes *through* every turtle waypoint.
//   4. Particle sampler pre-computes N evenly-spaced arc-length positions
//      along the full spline; SPH particles index into this LUT and advance
//      each tick, giving smooth constant-speed flow.
//
// ─── Typical usage ───────────────────────────────────────────────────────────
//   const morph = new Morphogenesis({
//     axiom: 'X',
//     rules: { X: 'F+[[X]-X]-F[-FX]+X', F: 'FF' },
//     iterations: 5,
//     angle: 25,
//   });
//   morph.generate(srcX, srcY, dstX, dstY);
//
//   // Render: getSplinePath() → SVG path string or WebGPU line strip
//   const pathD = morph.getSVGPath();
//
//   // Physics: advance particles
//   morph.tickParticles(dt);
//   const pts = morph.getParticlePositions();  // Float32Array [x0,y0, x1,y1,…]
//
// ─── References ──────────────────────────────────────────────────────────────
//   Prusinkiewicz & Lindenmayer – "The Algorithmic Beauty of Plants" (1990)
//   Catmull-Rom → cubic Bézier conversion via Shoemake (1987)
//   Arc-length parameterisation: Guenter & Parent (1990)

// ─── Public configuration ─────────────────────────────────────────────────────

/** Built-in named L-system presets. */








export type LSystemPreset =
  | 'FERN'          // Barnsley-style fern frond
  | 'ALGAE'         // Lindenmayer's original algae model
  | 'BUSH'          // Symmetrical bush / dendritic tree
  | 'SIERPINSKI'    // Sierpiński arrowhead curve (space-filling)
  | 'DRAGON'        // Heighway dragon curve
  | 'CUSTOM';       // Caller supplies axiom + rules

export interface LSystemDef {
  axiom: string;
  /** Rewriting rules: symbol → replacement string. */
  rules: Record<string, string>;
  /**
   * Turn angle in degrees applied to '+' (left) and '−' (right) symbols.
   * Some presets override this internally.
   */
  angle: number;
}

export interface MorphogenesisConfig {
  // ── L-system grammar ───────────────────────────────────────────────────────
  /** Choose a built-in preset or supply your own via axiom/rules/angle. */
  preset?: LSystemPreset;
  /** Custom axiom (used when preset is 'CUSTOM' or absent). */
  axiom?: string;
  /** Custom production rules. */
  rules?: Record<string, string>;
  /** Turn angle (degrees). Default 25. */
  angle?: number;
  /** Number of rewriting iterations.  More = denser fractal. Default 4. */
  iterations?: number;

  // ── Turtle geometry ────────────────────────────────────────────────────────
  /** Base step length at iteration depth 0 (pixels). Default 20. */
  stepLength?: number;
  /**
   * Shrink factor applied to stepLength per iteration.
   * finalStep = stepLength * (stepScale ** iterations).  Default 0.5.
   */
  stepScale?: number;
  /**
   * Maximum branch-stack depth to include in the output path.
   * 0 = trunk only, 1 = trunk + first-order branches, … Default 2.
   */
  maxBranchDepth?: number;

  // ── Bézier smoothing ───────────────────────────────────────────────────────
  /**
   * Catmull-Rom tension parameter (0 = loose, 1 = tight).
   * Controls how sharply the curve hugs each waypoint. Default 0.5.
   */
  tension?: number;

  // ── Particle flow ──────────────────────────────────────────────────────────
  /** Number of particles streaming along the path. Default 32. */
  particleCount?: number;
  /** Particle speed in path-length units per second. Default 60. */
  particleSpeed?: number;
  /** Arc-length LUT resolution (samples per Bézier segment). Default 20. */
  lutResolution?: number;

  // ── Domain ─────────────────────────────────────────────────────────────────
  /** Seed for the deterministic PRNG used to jitter branch angles. Default 42. */
  seed?: number;
}

// ─── Internal structures ──────────────────────────────────────────────────────

interface Waypoint {
  x: number;
  y: number;
  depth: number; // branch-stack depth at which this point was generated
}

interface BezierSegment {
  p0x: number; p0y: number;
  p1x: number; p1y: number; // control 1
  p2x: number; p2y: number; // control 2
  p3x: number; p3y: number;
  arcLength: number;        // pre-computed length of this segment
  cumLength: number;        // cumulative length up to end of this segment
}

interface TurtleState {
  x: number;
  y: number;
  angle: number; // degrees, 0 = rightward
  depth: number;
}

// ─── Deterministic LCG PRNG ──────────────────────────────────────────────────

class LCG {
  private s: number;
  constructor(seed: number) { this.s = seed >>> 0; }
  next(): number {
    this.s = Math.imul(1664525, this.s) + 1013904223;
    return (this.s >>> 0) / 0x100000000;
  }
  /** Uniform in [lo, hi). */
  range(lo: number, hi: number): number { return lo + this.next() * (hi - lo); }
}

// ─── Preset definitions ───────────────────────────────────────────────────────

const PRESETS: Record<Exclude<LSystemPreset, 'CUSTOM'>, LSystemDef> = {
  FERN: {
    axiom: 'X',
    rules: {
      X: 'F+[[X]-X]-F[-FX]+X',
      F: 'FF',
    },
    angle: 25,
  },
  ALGAE: {
    axiom: 'A',
    rules: {
      A: 'AB',
      B: 'A',
    },
    angle: 0, // no turning — purely linear growth; geometry via length
  },
  BUSH: {
    axiom: 'F',
    rules: {
      F: 'FF+[+F-F-F]-[-F+F+F]',
    },
    angle: 22.5,
  },
  SIERPINSKI: {
    axiom: 'F-G-G',
    rules: {
      F: 'F-G+F+G-F',
      G: 'GG',
    },
    angle: 120,
  },
  DRAGON: {
    axiom: 'FX',
    rules: {
      X: 'X+YF+',
      Y: '-FX-Y',
    },
    angle: 90,
  },
};

// ─── Main class ───────────────────────────────────────────────────────────────

export class Morphogenesis {
  // configuration (resolved)
  private readonly axiom: string;
  private readonly rules: Record<string, string>;
  private readonly angleDeg: number;
  private readonly iterations: number;
  private readonly stepLength: number;
  private readonly stepScale: number;
  private readonly maxBranchDepth: number;
  private readonly tension: number;
  private readonly particleCount: number;
  private readonly particleSpeed: number;
  private readonly lutResolution: number;
  private readonly rng: LCG;

  // computed geometry
  private waypoints: Waypoint[] = [];
  private segments: BezierSegment[] = [];
  private totalLength = 0;

  // particle state — phase in [0, totalLength), wraps around
  private particlePhase: Float64Array;

  // transform applied during generate()
  private originX = 0;
  private originY = 0;
  private scaleX = 1;
  private scaleY = 1;
  private rotationRad = 0;

  constructor(cfg: MorphogenesisConfig = {}) {
    // resolve grammar from preset or custom
    const preset =
      cfg.preset && cfg.preset !== 'CUSTOM' ? PRESETS[cfg.preset] : null;

    this.axiom    = cfg.axiom  ?? preset?.axiom  ?? 'F';
    this.rules    = cfg.rules  ?? preset?.rules  ?? {};
    this.angleDeg = cfg.angle  ?? preset?.angle  ?? 25;

    this.iterations     = cfg.iterations     ?? 4;
    this.stepLength     = cfg.stepLength     ?? 20;
    this.stepScale      = cfg.stepScale      ?? 0.5;
    this.maxBranchDepth = cfg.maxBranchDepth ?? 2;
    this.tension        = cfg.tension        ?? 0.5;
    this.particleCount  = cfg.particleCount  ?? 32;
    this.particleSpeed  = cfg.particleSpeed  ?? 60;
    this.lutResolution  = cfg.lutResolution  ?? 20;
    this.rng            = new LCG(cfg.seed ?? 42);

    this.particlePhase = new Float64Array(this.particleCount);
    // stagger initial phases so particles are spread across the path
    for (let i = 0; i < this.particleCount; i++) {
      this.particlePhase[i] = i / this.particleCount; // normalised [0,1)
    }
  }

  // ── 1. L-system string expansion ─────────────────────────────────────────

  private expand(): string {
    let s = this.axiom;
    for (let i = 0; i < this.iterations; i++) {
      let next = '';
      for (const ch of s) {
        next += this.rules[ch] ?? ch;
      }
      s = next;
      // Safety: cap expansion at ~200 k chars to avoid freeze
      if (s.length > 200_000) break;
    }
    return s;
  }

  // ── 2. Turtle interpreter ─────────────────────────────────────────────────

  private interpret(
    lstring: string,
    startX: number,
    startY: number,
    startAngle: number,
  ): Waypoint[] {
    const step = this.stepLength * Math.pow(this.stepScale, this.iterations);
    const angleRad = (this.angleDeg * Math.PI) / 180;

    const stack: TurtleState[] = [];
    let state: TurtleState = {
      x: startX,
      y: startY,
      angle: startAngle,
      depth: 0,
    };

    const waypoints: Waypoint[] = [{ x: state.x, y: state.y, depth: 0 }];

    for (const ch of lstring) {
      switch (ch) {
        case 'F':
        case 'G': {
          // Move forward and draw
          const nx = state.x + step * Math.cos(state.angle);
          const ny = state.y + step * Math.sin(state.angle);
          state.x = nx;
          state.y = ny;
          if (state.depth <= this.maxBranchDepth) {
            waypoints.push({ x: nx, y: ny, depth: state.depth });
          }
          break;
        }
        case 'f': {
          // Move forward without drawing (pen-up)
          state.x += step * Math.cos(state.angle);
          state.y += step * Math.sin(state.angle);
          break;
        }
        case '+': {
          // Turn left
          state.angle -= angleRad;
          break;
        }
        case '-': {
          // Turn right
          state.angle += angleRad;
          break;
        }
        case '[': {
          // Push state (start branch)
          stack.push({ ...state });
          state.depth += 1;
          break;
        }
        case ']': {
          // Pop state (end branch) — insert NaN sentinel to break the poly-line
          if (state.depth <= this.maxBranchDepth) {
            waypoints.push({ x: NaN, y: NaN, depth: state.depth });
          }
          const popped = stack.pop();
          if (popped) state = popped;
          break;
        }
        case '|': {
          // U-turn
          state.angle += Math.PI;
          break;
        }
        // All other symbols (variables) ignored geometrically
      }
    }

    return waypoints;
  }

  // ── 3. Catmull-Rom → cubic Bézier conversion ─────────────────────────────
  //
  //   Given four Catmull-Rom control points P0…P3 and tension α,
  //   the corresponding cubic Bézier is:
  //     BP1 = P1 + (P2 - P0) / (6α)
  //     BP2 = P2 - (P3 - P1) / (6α)
  //   where BP0 = P1, BP3 = P2.
  //
  //   This guarantees C1 continuity and interpolation through every waypoint.

  private catmullRomToBezier(pts: Array<[number, number]>): BezierSegment[] {
    if (pts.length < 2) return [];

    const alpha = this.tension > 0 ? 6 * this.tension : 1e-6;
    const segs: BezierSegment[] = [];
    let cumLen = 0;

    // Pad with phantom endpoints so we have P0 at index -1 and Pn+1
    const all: Array<[number, number]> = [
      [2 * pts[0][0] - pts[1][0], 2 * pts[0][1] - pts[1][1]],
      ...pts,
      [
        2 * pts[pts.length - 1][0] - pts[pts.length - 2][0],
        2 * pts[pts.length - 1][1] - pts[pts.length - 2][1],
      ],
    ];

    for (let i = 1; i < all.length - 2; i++) {
      const [p0x, p0y] = all[i - 1];
      const [p1x, p1y] = all[i];
      const [p2x, p2y] = all[i + 1];
      const [p3x, p3y] = all[i + 2];

      const bp1x = p1x + (p2x - p0x) / alpha;
      const bp1y = p1y + (p2y - p0y) / alpha;
      const bp2x = p2x - (p3x - p1x) / alpha;
      const bp2y = p2y - (p3y - p1y) / alpha;

      const arcLen = this.bezierArcLength(
        p1x, p1y, bp1x, bp1y, bp2x, bp2y, p2x, p2y,
      );
      cumLen += arcLen;

      segs.push({
        p0x: p1x, p0y: p1y,
        p1x: bp1x, p1y: bp1y,
        p2x: bp2x, p2y: bp2y,
        p3x: p2x, p3y: p2y,
        arcLength: arcLen,
        cumLength: cumLen,
      });
    }

    return segs;
  }

  /** Approximate cubic Bézier arc-length via Gaussian quadrature (5-point). */
  private bezierArcLength(
    p0x: number, p0y: number,
    p1x: number, p1y: number,
    p2x: number, p2y: number,
    p3x: number, p3y: number,
  ): number {
    // 5-point Legendre-Gauss nodes/weights on [0,1]
    const nodes   = [0.046910077781, 0.230765345791, 0.5, 0.769234654209, 0.953089922219];
    const weights = [0.118463442528, 0.239314335249, 0.284444444444, 0.239314335249, 0.118463442528];

    let len = 0;
    for (let k = 0; k < 5; k++) {
      const t = nodes[k];
      const mt = 1 - t;
      // derivative of cubic Bézier: 3[(1-t)²(P1-P0) + 2(1-t)t(P2-P1) + t²(P3-P2)]
      const dx = 3 * (
        mt * mt * (p1x - p0x) +
        2 * mt * t * (p2x - p1x) +
        t  * t  * (p3x - p2x)
      );
      const dy = 3 * (
        mt * mt * (p1y - p0y) +
        2 * mt * t * (p2y - p1y) +
        t  * t  * (p3y - p2y)
      );
      len += weights[k] * Math.sqrt(dx * dx + dy * dy);
    }
    return len;
  }

  /** Evaluate a cubic Bézier at parameter t ∈ [0,1]. */
  private evalBezier(seg: BezierSegment, t: number): [number, number] {
    const mt = 1 - t;
    const mt2 = mt * mt;
    const mt3 = mt2 * mt;
    const t2 = t * t;
    const t3 = t2 * t;
    return [
      mt3 * seg.p0x + 3 * mt2 * t * seg.p1x + 3 * mt * t2 * seg.p2x + t3 * seg.p3x,
      mt3 * seg.p0y + 3 * mt2 * t * seg.p1y + 3 * mt * t2 * seg.p2y + t3 * seg.p3y,
    ];
  }

  // ── 4. Arc-length parameterisation ───────────────────────────────────────

  /**
   * Map a distance s ∈ [0, totalLength] to world coordinates by binary-
   * searching the segment cumulative-length table.
   */
  private sampleAtLength(s: number): [number, number] {
    if (this.segments.length === 0) return [this.originX, this.originY];
    s = Math.max(0, Math.min(s, this.totalLength));

    // Find segment via binary search on cumLength
    let lo = 0, hi = this.segments.length - 1;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (this.segments[mid].cumLength < s) lo = mid + 1;
      else hi = mid;
    }
    const seg = this.segments[lo];
    const prevCum = lo > 0 ? this.segments[lo - 1].cumLength : 0;
    const localS = s - prevCum;
    const t = seg.arcLength > 0 ? Math.min(localS / seg.arcLength, 1) : 0;
    return this.evalBezier(seg, t);
  }

  // ── 5. Coordinate transform helpers ──────────────────────────────────────

  /**
   * Compute the rotation + uniform scale that maps the turtle's natural
   * direction (rightward, +X) to the vector (src → dst), then offsets so
   * the path starts at (srcX, srcY).
   */
  private computeTransform(
    srcX: number, srcY: number,
    dstX: number, dstY: number,
  ): void {
    const dx = dstX - srcX;
    const dy = dstY - srcY;
    const dist = Math.sqrt(dx * dx + dy * dy) || 1;

    this.originX    = srcX;
    this.originY    = srcY;
    this.rotationRad = Math.atan2(dy, dx);
    // scale so the raw turtle extent maps to the edge length
    this.scaleX = dist / Math.max(this.totalLength, 1);
    this.scaleY = this.scaleX;
  }

  // ── 6. Public API ─────────────────────────────────────────────────────────

  /**
   * (Re)generate the L-system path from (srcX, srcY) to (dstX, dstY).
   * The turtle is aligned and scaled so the trunk naturally spans the edge.
   *
   * Call this once per edge, or whenever the endpoint positions change.
   */
  generate(
    srcX: number, srcY: number,
    dstX: number, dstY: number,
  ): void {
    const lstring = this.expand();

    // First pass: run the turtle in canonical space (starts at origin, heads right)
    const rawWaypoints = this.interpret(lstring, 0, 0, 0);

    // Split into continuous poly-line segments at NaN sentinels
    const polylines: Array<[number, number][]> = [];
    let current: Array<[number, number]> = [];

    for (const wp of rawWaypoints) {
      if (isNaN(wp.x)) {
        if (current.length >= 2) polylines.push(current);
        current = [];
      } else {
        current.push([wp.x, wp.y]);
      }
    }
    if (current.length >= 2) polylines.push(current);

    // Build Bézier segments for each continuous poly-line
    this.segments = [];
    let cum = 0;
    for (const poly of polylines) {
      const segs = this.catmullRomToBezier(poly);
      for (const s of segs) {
        s.cumLength += cum;
        this.segments.push(s);
      }
      if (segs.length > 0) cum = segs[segs.length - 1].cumLength;
    }
    this.totalLength = this.segments.length > 0
      ? this.segments[this.segments.length - 1].cumLength
      : 0;

    // Compute the transform to fit the path from src to dst
    this.computeTransform(srcX, srcY, dstX, dstY);

    // Re-stagger particles across the new path
    for (let i = 0; i < this.particleCount; i++) {
      this.particlePhase[i] = (i / this.particleCount) * this.totalLength;
    }

    this.waypoints = rawWaypoints;
  }

  // ── Transform raw turtle coords into world space ──────────────────────────

  private toWorld(tx: number, ty: number): [number, number] {
    const cos = Math.cos(this.rotationRad);
    const sin = Math.sin(this.rotationRad);
    const sx  = tx * this.scaleX;
    const sy  = ty * this.scaleY;
    return [
      this.originX + sx * cos - sy * sin,
      this.originY + sx * sin + sy * cos,
    ];
  }

  /**
   * Advance all particle phases by dt seconds and return their world-space
   * positions as a flat Float32Array [x0,y0, x1,y1, …].
   */
  tickParticles(dt: number): Float32Array {
    if (this.totalLength === 0) {
      return new Float32Array(this.particleCount * 2).fill(this.originX);
    }
    const advance = this.particleSpeed * dt;
    const out = new Float32Array(this.particleCount * 2);

    for (let i = 0; i < this.particleCount; i++) {
      this.particlePhase[i] = (this.particlePhase[i] + advance) % this.totalLength;
      const [tx, ty] = this.sampleAtLength(this.particlePhase[i]);
      const [wx, wy] = this.toWorld(tx, ty);
      out[i * 2]     = wx;
      out[i * 2 + 1] = wy;
    }
    return out;
  }

  /** Current particle positions without advancing time. */
  getParticlePositions(): Float32Array {
    return this.tickParticles(0);
  }

  /**
   * Returns an SVG path string (`d` attribute) for the entire spline,
   * suitable for `<path d={…} />` or a WebGPU debug overlay.
   *
   * Multiple disconnected sub-paths (branches) are separated by 'M' moveto
   * commands so the SVG renderer draws them as individual open curves.
   */
  getSVGPath(): string {
    if (this.segments.length === 0) return '';
    const parts: string[] = [];
    let prevEnd: [number, number] | null = null;

    for (const seg of this.segments) {
      const [p0wx, p0wy] = this.toWorld(seg.p0x, seg.p0y);
      const [p1wx, p1wy] = this.toWorld(seg.p1x, seg.p1y);
      const [p2wx, p2wy] = this.toWorld(seg.p2x, seg.p2y);
      const [p3wx, p3wy] = this.toWorld(seg.p3x, seg.p3y);

      const startsDifferent =
        prevEnd === null ||
        Math.abs(prevEnd[0] - p0wx) > 0.5 ||
        Math.abs(prevEnd[1] - p0wy) > 0.5;

      if (startsDifferent) {
        parts.push(`M ${f(p0wx)} ${f(p0wy)}`);
      }
      parts.push(`C ${f(p1wx)} ${f(p1wy)} ${f(p2wx)} ${f(p2wy)} ${f(p3wx)} ${f(p3wy)}`);
      prevEnd = [p3wx, p3wy];
    }

    return parts.join(' ');
  }

  /**
   * Returns the spline as a flat Float32Array of world-space sample points
   * [x0,y0, x1,y1, …], suitable for a WebGPU PRIMITIVE_TOPOLOGY_LINE_STRIP.
   *
   * Disconnected sub-paths are separated by (NaN, NaN) pairs so the GPU
   * strip renderer skips the invisible connector segment.
   */
  getLineStrip(samplesPerSegment = 12): Float32Array {
    if (this.segments.length === 0) return new Float32Array(0);

    const out: number[] = [];
    let prevSeg: BezierSegment | null = null;

    for (const seg of this.segments) {
      const [p0wx, p0wy] = this.toWorld(seg.p0x, seg.p0y);

      const isDisconnected =
        prevSeg !== null &&
        (Math.abs(prevSeg.p3x - seg.p0x) > 0.5 ||
         Math.abs(prevSeg.p3y - seg.p0y) > 0.5);

      if (prevSeg === null) {
        out.push(p0wx, p0wy);
      } else if (isDisconnected) {
        out.push(NaN, NaN, p0wx, p0wy);
      }

      for (let k = 1; k <= samplesPerSegment; k++) {
        const t = k / samplesPerSegment;
        const [tx, ty] = this.evalBezier(seg, t);
        const [wx, wy] = this.toWorld(tx, ty);
        out.push(wx, wy);
      }
      prevSeg = seg;
    }

    return new Float32Array(out);
  }

  // ── Introspection ─────────────────────────────────────────────────────────

  /** Total arc-length of all Bézier segments (world-space pixels). */
  get pathLength(): number { return this.totalLength; }

  /** Number of Bézier segments currently in the path. */
  get segmentCount(): number { return this.segments.length; }

  /**
   * Sample a single world-space point at normalised path position t ∈ [0,1].
   * Useful for placing labels or decorations along the edge.
   */
  sampleNormalised(t: number): [number, number] {
    const [tx, ty] = this.sampleAtLength(t * this.totalLength);
    return this.toWorld(tx, ty);
  }

  /**
   * Tangent direction (radians) at normalised path position t.
   * Forward-differences two nearby samples.
   */
  tangentAt(t: number): number {
    const eps = 0.001;
    const [ax, ay] = this.sampleNormalised(Math.max(0, t - eps));
    const [bx, by] = this.sampleNormalised(Math.min(1, t + eps));
    return Math.atan2(by - ay, bx - ax);
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Format a number to 2 d.p. for SVG paths. */
function f(n: number): string { return n.toFixed(2); }

// ─── Convenience factory ──────────────────────────────────────────────────────

/**
 * Create a Morphogenesis instance from a named preset.
 *
 * @example
 * const edge = fromPreset('FERN', { iterations: 5, particleCount: 64 });
 * edge.generate(100, 300, 700, 300);
 * animate(() => edge.tickParticles(1/60));
 */
export function fromPreset(
  preset: Exclude<LSystemPreset, 'CUSTOM'>,
  overrides: Omit<MorphogenesisConfig, 'preset' | 'axiom' | 'rules' | 'angle'> = {},
): Morphogenesis {
  return new Morphogenesis({ preset, ...overrides });
}

/**
 * All available preset names for UI dropdowns.
 */
export const PRESET_NAMES: Exclude<LSystemPreset, 'CUSTOM'>[] = [
  'FERN', 'ALGAE', 'BUSH', 'SIERPINSKI', 'DRAGON',
];
